"use client";
import { useState } from "react";
import { AcuasShell, PageHeader, ProductCard, products } from "@/components/acuas-shell";

export default function ProductsPage(){
  const [filter,setFilter]=useState("Tất cả");
  const shown=filter==="Tất cả"?products:products.filter(p=>filter==="Bình lớn"?p.name.includes("Bình"):p.name.includes("Chai"));
  return <AcuasShell active="/san-pham"><PageHeader title="Sản phẩm DAKAWA" intro="Nước uống đóng bình và đóng chai cho gia đình, doanh nghiệp, hospitality và sự kiện."/><section className="container-fluid py-5"><div className="container py-5"><div className="text-center mx-auto pb-4 section-title"><h4 className="text-uppercase text-primary">Danh mục sản phẩm</h4><h1>Chọn nước theo nhu cầu sử dụng</h1><p>Chọn dung tích phù hợp và liên hệ để xác nhận giá, số chai mỗi thùng cùng chính sách giao nhận.</p></div><div className="catalog-filters mb-5">{["Tất cả","Bình lớn","Chai đóng thùng"].map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?"active":""}>{x}</button>)}</div><div className="row g-4 justify-content-center">{shown.map(product=><div className="col-md-6 col-lg-4" key={product.name}><ProductCard product={product}/></div>)}</div></div></section><section className="container-fluid bg-light py-5"><div className="container py-5"><div className="row g-5"><div className="col-lg-5"><h1 className="display-4 mb-4">Thông tin trước khi đặt nước</h1><p>Để được tư vấn nhanh, hãy chuẩn bị địa chỉ giao, dung tích, số lượng và số vỏ bình cần đổi. DAKAWA sẽ xác nhận chi phí và thời gian giao khi tiếp nhận yêu cầu.</p></div><div className="col-lg-7"><div className="row g-3">{[["fa-tags","Giá bán hiện hành"],["fa-box","Số chai mỗi thùng"],["fa-exchange-alt","Cọc và đổi vỏ bình"],["fa-truck","Số lượng giao tối thiểu"],["fa-map-marker-alt","Phí theo khu vực"],["fa-credit-card","Hình thức thanh toán"]].map(([icon,text])=><div className="col-md-6" key={text}><div className="document-box d-flex align-items-center gap-3"><i className={`fas ${icon}`}/><strong>{text}</strong></div></div>)}</div></div></div></div></section></AcuasShell>
}
